on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3   
      # Run your project's build step
      - name: Build
        run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
            accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
            directory: .next
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}